### ISSUE TITLE
aws_ebs_volume resource fails at adding tags.

### ISSUE THREAD

**Issue by samof76** [sous-chefs/aws#340]
### Cookbook version
ab6fbe72196ba885e7684266d63f2b6a813aa819

### Chef-client version
Chef 12.13.37

### Platform Details
Amazon Linux

### Scenario:
Trying to create an EBS Volume and attached

### Steps to Reproduce:
Using opsworks, trying to create an EBS volume from, using the following the resource parameter.

```ruby
aws_ebs_volume 'data volume for app' do
  size 100
  volume_type "standard"
  availability_zone "#{availability_zone}"
  device '/dev/sdh'
  encrypted true
  kms_key_id node[:custom_ebs][:kms_key_id]
  action [:create, :attach]
end
```

### Expected Result:
The volume need to get created and attached to the instance.

### Actual Result:
Volume does get created but fails at created tags for it.

```log
NoMethodError
-------------
undefined method `empty?' for nil:NilClass
 
Cookbook Trace:
---------------
/var/chef/runs/d446bd3c-6808-4925-9dd8-8028b504bd57/local-mode-cache/cache/cookbooks/aws/resources/ebs_volume.rb:361:in `add_tags'
/var/chef/runs/d446bd3c-6808-4925-9dd8-8028b504bd57/local-mode-cache/cache/cookbooks/aws/resources/ebs_volume.rb:66:in `block (2 levels) in class_from_file'
/var/chef/runs/d446bd3c-6808-4925-9dd8-8028b504bd57/local-mode-cache/cache/cookbooks/aws/resources/ebs_volume.rb:57:in `block in class_from_file'
 ```

**Comment by samof76** [comment]
But passing the tags with an empty hash like the following.

```ruby
aws_ebs_volume 'data volume for app' do
...
  tags ({})
....
  action [:create, :attach]
end
```
We can bypass the error.
